name: Upload Software to TIRA
on: workflow_dispatch
env:
  SRC_PATH: clef25/retrieval-augmented-debating/debating-systems/basic-elastic-py
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip3 install tira
      - name: Build, test, and upload image
        run: |
          docker build -t registry.webis.de/code-research/tira/tira-user-aristotle/github-action-submission:0.0.1 -f ${{ env.SRC_PATH }}/Dockerfile ${{ env.SRC_PATH }}
          tira-run --tira-client-token ${{ secrets.TIRA_CLIENT_TOKEN_ARISTOTLE }} --input-dataset retrieval-augmented-debating-2025/rad25-2025-01-16-toy-20250116-training --image registry.webis.de/code-research/tira/tira-user-aristotle/github-action-submission:0.0.1 --command '/genirsim/run.sh --configuration-file=$inputDataset/*.json --parameter-file=$inputDataset/*.tsv --output-file=$outputDir/simulations.jsonl' --allow-network true --push true --fail-if-output-is-empty
