name: Publish RAD25 base image to GitHub Packages

on:
  push:
    tags:
      - rad25-base-v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: touche-webis-de/touche25-retrieval-augmented-debating-base
  IMAGE_TITLE: "touche-rad25-base"
  IMAGE_DESCRIPTION: "Base image for the Retrieval-Augmented Debating 2025 task"
  SRC_PATH: clef25/retrieval-augmented-debating/debating-systems/base/

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=v(\d.\d.\d),group=1
            type=match,pattern=v(\d.\d),group=1
            type=match,pattern=v(\d),group=1
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_TITLE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.url=https://github.com/touche-webis-de/touche-code/tree/main/${{ env.SRC_PATH }}
            org.opencontainers.image.source=https://github.com/touche-webis-de/touche-code/tree/main/${{ env.SRC_PATH }}

      - name: Extract tags for Docker (py3.13)
        id: metapy
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=v(\d.\d.\d),group=1
            type=match,pattern=v(\d.\d),group=1
            type=match,pattern=v(\d),group=1
          flavor: |
            suffix=-py3.13

      - name: Extract tags for Docker (pytorch2.5.1)
        id: metapytorch
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=match,pattern=v(\d.\d.\d),group=1
            type=match,pattern=v(\d.\d),group=1
            type=match,pattern=v(\d),group=1
          flavor: |
            suffix=-pytorch2.5.1

      - name: Build and push Docker image (py3.13)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SRC_PATH }}
          push: true
          tags: ${{ steps.metapy.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            version:${{ steps.meta.outputs.version }}
            BASE_IMAGE=python:3.13-slim

      - name: Build and push Docker image (pytorch2.5.1)
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SRC_PATH }}
          push: true
          tags: ${{ steps.metapytorch.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            version:${{ steps.meta.outputs.version }}
            BASE_IMAGE=pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SRC_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: version:${{ steps.meta.outputs.version }}

